name: netease_cloud_music_api
description: 网易云音乐 Dart 版 API
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  pointycastle: ^3.6.1
  convert: ^3.1.0
  http: ^1.1.0
  asn1lib: ^1.4.0

dev_dependencies:
  test: ^1.21.0
